import { useCase } from '../context/CaseContext';
import { useAnalysisResult, useExplainability } from '../hooks/useResearchData';
import { DataState, EmptyState, ResearchBadge } from '../components/common/ResearchStates';
import { disclaimer } from '../lib/format';
export default function Explainability() {
  const { caseId } = useCase(); const explanation = useExplainability(caseId); const patient = useAnalysisResult(caseId);
  if (!caseId) return <EmptyState title="No active case" detail="Select an existing case on the Analyze page."/>;
  return <div className="space-y-6"><header><ResearchBadge/><h1 className="mt-3 font-heading text-2xl">Explainability · Grad-CAM</h1><p className="mt-2 font-mono text-xs text-muted">CASE {caseId}</p></header><DataState loading={explanation.isLoading || patient.isLoading} error={explanation.error ?? patient.error} retry={() => { void explanation.refetch(); void patient.refetch(); }}>{explanation.data && <><div className="grid gap-5 lg:grid-cols-[2fr_1fr]"><section className="rounded-card border border-border bg-surface p-5"><div className="flex aspect-video items-center justify-center border border-border bg-black p-6 text-center"><p className="max-w-md font-mono text-xs leading-6 text-muted">{explanation.data.available ? 'Grad-CAM artifact exists on the backend, but this API does not serve image bytes. Image overlay and slice controls are unavailable until a secure image endpoint is added.' : 'Grad-CAM artifact not available for this case.'}</p></div><p className="mt-3 font-mono text-xs text-muted">Original MRI: Not available · Heatmap overlay: Not available · Synchronized slice control: Not available</p></section><section className="rounded-card border border-border bg-surface p-5"><h2 className="font-heading text-lg">Method metadata</h2><dl className="mt-4 space-y-3 text-sm"><div>Method: <strong>{patient.data?.explainability?.method ?? 'Grad-CAM'}</strong></div><div>Target layer: <strong>{patient.data?.explainability?.target_layer ?? 'Not available'}</strong></div><div>Artifact availability: <strong>{explanation.data.available ? 'Available on server; not served by API' : 'Not available'}</strong></div></dl><p className="mt-6 font-mono text-xs text-muted">Low influence → High influence · Color scale unavailable without image data.</p></section></div><section className="rounded-card border border-border bg-surface p-5"><h2 className="font-heading text-lg">How to read this</h2><p className="mt-3 text-sm leading-6 text-muted">Grad-CAM saliency maps can highlight regions that influenced the model output. They are not proof of causation or pathology. Without image data served by the backend, no heatmap or regional claim is displayed.</p></section><p className="text-xs text-muted">{disclaimer}</p></>}</DataState></div>;
}
