import { useState } from 'react';
import { Button } from '../components/ui/button';
import { DataState, EmptyState } from '../components/common/ResearchStates';
import { useCase } from '../context/CaseContext';
import { useAnalysisResult, useExplainability } from '../hooks/useResearchData';
import { dateTime, disclaimer, percent } from '../lib/format';
import type { PatientReport, ExplanationResponse } from '../types/api';
function reportText(report: PatientReport, explanation?: ExplanationResponse) { return ['CerebraQ — Patient-level research report', disclaimer, `Case ID: ${report.patient_id}`, `Generated: ${dateTime(report.generated_at)}`, `Model prediction: ${report.model_prediction.class}`, `HGG probability: ${percent(report.model_prediction.hgg_probability)}`, `Model confidence: ${percent(report.model_prediction.model_confidence)}`, `Ground truth: ${report.ground_truth?.available ? report.ground_truth.class : 'Not available'}`, `Tumour pixels: ${report.tumor_roi?.tumor_pixels ?? 'Not available'}`, `ROI pixels: ${report.tumor_roi?.roi_pixels ?? 'Not available'}`, `Tumour fraction: ${percent(report.tumor_roi?.tumor_fraction)}`, `MRI modalities: ${report.mri_modalities.join(', ')}`, `Explainability: ${report.explainability?.method ?? 'Not available'}`, `Visualization availability: ${explanation?.available ? 'Artifact exists on server; image not exposed by API' : 'Not available'}`, 'Saliency does not establish causation or pathology.', disclaimer].join('\n'); }
function ReportSheet({ report, explanation }: { report: PatientReport; explanation?: ExplanationResponse }) { return <article className="report-sheet mx-auto max-w-4xl rounded-card border border-border bg-surface p-6 sm:p-10"><p className="border-b border-border pb-4 text-sm font-semibold text-warning">{disclaimer}</p><h2 className="mt-8 font-heading text-2xl">CerebraQ · Patient-level research report</h2><p className="mt-2 font-mono text-xs">CASE {report.patient_id} · {dateTime(report.generated_at)}</p><dl className="mt-8 grid gap-5 border-y border-border py-6 text-sm sm:grid-cols-2"><div>Predicted class: <strong>{report.model_prediction.class}</strong></div><div>Model confidence: <strong className="font-mono">{percent(report.model_prediction.model_confidence)}</strong></div><div>HGG probability: <strong className="font-mono">{percent(report.model_prediction.hgg_probability)}</strong></div><div>Ground truth: <strong>{report.ground_truth?.available ? report.ground_truth.class : 'Not available'}</strong></div><div>Tumour pixels: <strong className="font-mono">{report.tumor_roi?.tumor_pixels ?? 'Not available'}</strong></div><div>ROI pixels: <strong className="font-mono">{report.tumor_roi?.roi_pixels ?? 'Not available'}</strong></div><div>Tumour fraction: <strong className="font-mono">{percent(report.tumor_roi?.tumor_fraction)}</strong></div><div>Modalities: <strong>{report.mri_modalities.join(' · ') || 'Not available'}</strong></div></dl><h3 className="mt-7 font-heading text-lg">Explainability</h3><p className="mt-2 text-sm">{report.explainability?.method ?? 'Not available'} · Target layer: {report.explainability?.target_layer ?? 'Not available'}.</p><p className="mt-2 text-sm">Image: {explanation?.available ? 'Available on server; current API does not serve image bytes.' : 'Not available'}. Saliency does not establish causation or pathology.</p><p className="mt-8 border-t border-border pt-4 text-sm font-semibold">{disclaimer}</p></article>; }
export default function Reports() { const { caseId } = useCase(); const patient = useAnalysisResult(caseId); const explanation = useExplainability(caseId); const [copyStatus, setCopyStatus] = useState('');
  if (!caseId) return <EmptyState title="No active case" detail="Select a case on the Analyze page to create a report view from actual API data."/>;
  return <div className="space-y-5"><div className="flex flex-wrap items-center justify-between gap-3 print:hidden"><h1 className="font-heading text-2xl">Research report</h1><div className="flex flex-wrap gap-2"><Button variant="outline" disabled={!patient.data} onClick={() => window.print()}>Print / Save as PDF</Button><Button variant="outline" disabled={!patient.data} onClick={() => { if (!patient.data) return; if (!navigator.clipboard?.writeText) { setCopyStatus('Clipboard unavailable in this context.'); return; } void navigator.clipboard.writeText(reportText(patient.data, explanation.data)).then(() => setCopyStatus('Copied as text')).catch(() => setCopyStatus('Could not copy; check clipboard permissions.')); }}>Copy as text</Button></div></div><p role="status" className="print:hidden text-xs text-muted">{copyStatus}</p><DataState loading={patient.isLoading} error={patient.error} retry={() => { void patient.refetch(); }}>{patient.data && <><ReportSheet report={patient.data} explanation={explanation.data}/>{explanation.isPending && <p className="print:hidden text-xs text-muted">Checking image availability…</p>}{explanation.error && <p className="print:hidden text-xs text-warning">Image availability could not be retrieved. <button type="button" className="underline" onClick={() => { void explanation.refetch(); }}>Retry</button></p>}</>}</DataState></div>;
}
