import { useState } from 'react';
import { Button } from '../components/ui/button';
import { DataState, EmptyState } from '../components/common/ResearchStates';
import { useCase } from '../context/CaseContext';
import { useAnalysisResult, useExplainability } from '../hooks/useResearchData';
import { dateTime, disclaimer, percent } from '../lib/format';
import type { PatientReport, ExplanationResponse } from '../types/api';
function reportText(report: PatientReport, explanation?: ExplanationResponse) { return ['CerebraQ — Patient-level research report', disclaimer, `Case ID: ${report.patient_id}`, `Generated: ${dateTime(report.generated_at)}`, `Model prediction: ${report.model_prediction.class}`, `HGG probability: ${percent(report.model_prediction.hgg_probability)}`, `Model confidence: ${percent(report.model_prediction.model_confidence)}`, `Ground truth: ${report.ground_truth?.available ? report.ground_truth.class : 'Not available'}`, `Tumour pixels: ${report.tumor_roi?.tumor_pixels ?? 'Not available'}`, `ROI pixels: ${report.tumor_roi?.roi_pixels ?? 'Not available'}`, `Tumour fraction: ${percent(report.tumor_roi?.tumor_fraction)}`, `MRI modalities: ${report.mri_modalities.join(', ')}`, `Explainability: ${report.explainability?.method ?? 'Not available'}`, `Visualization availability: ${explanation?.available ? 'Artifact exists on server; image not exposed by API' : 'Not available'}`, 'Saliency does not establish causation or pathology.', disclaimer].join('\n'); }
export default function Reports() { const { caseId } = useCase(); const patient = useAnalysisResult(caseId); const explanation = useExplainability(caseId); const [copied, setCopied] = useState(false);
  if (!caseId) return <EmptyState title="No active case" detail="Select a case on the Analyze page to create a report view from actual API data."/>;
  return <div className="space-y-5"><div className="flex flex-wrap items-center justify-between gap-3 print:hidden"><h1 className="font-heading text-2xl">Research report</h1><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => window.print()}>Print / Save as PDF</Button><Button variant="outline" disabled={!patient.data} onClick={() => { if (!patient.data) return; void navigator.clipboard.writeText(reportText(patient.data, explanation.data)).then(() => setCopied(true)).catch(() => setCopied(false)); }}>{copied ? 'Copied' : 'Copy as text'}</Button></div></div><DataState loading={patient.isLoading || explanation.isLoading} error={patient.error ?? explanation.error} retry={() => { void patient.refetch(); void explanation.refetch(); }}>{patient.data && <article className="report-sheet mx-auto max-w-4xl rounded-card border border-border bg-surface p-6 sm:p-10"><p className="border-b border-border pb-4 text-sm font-semibold text-warning">{disclaimer}</p><h2 className="mt-8 font-heading text-2xl">CerebraQ · Patient-level research report</h2><p className="mt-2 font-mono text-xs">CASE {patient.data.patient_id} · {dateTime(patient.data.generated_at)}</p><dl className="mt-8 grid gap-5 border-y border-border py-6 text-sm sm:grid-cols-2"><div>Predicted class: <strong>{patient.data.model_prediction.class}</strong></div><div>Model confidence: <strong className="font-mono">{percent(patient.data.model_prediction.model_confidence)}</strong></div><div>HGG probability: <strong className="font-mono">{percent(patient.data.model_prediction.hgg_probability)}</strong></div><div>Ground truth: <strong>{patient.data.ground_truth?.available ? patient.data.ground_truth.class : 'Not available'}</strong></div><div>Tumour pixels: <strong className="font-mono">{patient.data.tumor_roi?.tumor_pixels ?? 'Not available'}</strong></div><div>ROI pixels: <strong className="font-mono">{patient.data.tumor_roi?.roi_pixels ?? 'Not available'}</strong></div><div>Tumour fraction: <strong className="font-mono">{percent(patient.data.tumor_roi?.tumor_fraction)}</strong></div><div>Modalities: <strong>{patient.data.mri_modalities.join(' · ')}</strong></div></dl><h3 className="mt-7 font-heading text-lg">Explainability</h3><p className="mt-2 text-sm">{patient.data.explainability?.method ?? 'Not available'} · Target layer: {patient.data.explainability?.target_layer ?? 'Not available'}.</p><p className="mt-2 text-sm">Image: {explanation.data?.available ? 'Available on server; current API does not serve image bytes.' : 'Not available'}. Saliency does not establish causation or pathology.</p><p className="mt-8 border-t border-border pt-4 text-sm font-semibold">{disclaimer}</p></article>}</DataState></div>;
}
